### ISSUE TITLE
[HS110 v.1.0] La puissance ne remonte pas

### ISSUE THREAD

**Issue by LuffyyyffuL** [kavod/kkasa#1]
Bonjour,

Je possède 2 prises TP_Link : 

1 - HS110 v.1.0 : La puissance ne remonte pas ou est très basse et fausse
2 - HS110 v.2.0 : ON / OFF / Puissance -> OK

Sinon, pour les deux prises, la "consumption" est identique, bizarre.

Merci pour le plugin en tout cas :)

**Comment by kavod** [comment]
Merci pour ton retour.

Je viens de faire une mise à jour... pas pour régler ton problème mais pour avoir des logs qui pourraient m'aider à mieux cerner ce qu'il se passe.

Peux-tu : 

- Installer dernière version (depuis github ou version "2018-11-30 18:14:40" sur le market "beta")
- Activer le plugin, installer les dépendances, configurer tes identifiants
- Passer en log level "Debug" sur ce plugin
- Synchroniser tes équipements
- Dans la page du plugin, un bouton "Debug" a dû apparaître. Click dessus.
- Et enfin, partage le contenu du log kkasa

Enfin, pour ce qui est des valeurs "basse et fausse" : est-ce que tu fais la comparaison avec ce que t'indique l'appli mobile "Kasa" ?

En te remerciant par avance

**Comment by kavod** [comment]
Bonjour,

Peux tu dérouler le processus indiquer plus haut pour me transmettre les logs ?

Merci.

**Comment by Peboli** [comment]
Bonjour,

Même problème d'affichage de la puissance et de la conso et de la tension pour moi également sur une HS110 en v.1.0
Plugin installé dans Jeedom via github.
En pièces jointes le log du debug et une capture d'écran de mon appli Kasa au moment du debug.
Les infos semblent y être mais n'apparaissent pas dans le widget ni en testant sur les commandes.
[debug_kkasa.log](https://github.com/kavod/kkasa/files/2640008/debug_kkasa.log)
![screenshot_20181203-160729_kasa](https://user-images.githubusercontent.com/16508054/49382310-69225900-f716-11e8-87a9-7cd8aa6187c4.jpg)

**Comment by kavod** [comment]
Bonjour @Peboli et merci pour ces informations près précieuses.

Plusieurs choses suite à ton message

1. J'ai pu remarqué que tu as anonymisé les longitudes/latitudes dans tes logs. C'est une très bonne chose et je me suis avant tout attaché à anonymiser automatiquement ces informations.
Suite à une réinstallation des dépendances, pourras-tu me confirmer que ça le fait bien ? Si ce n'est pas le cas, je te serais reconnaissant d'ouvrir un nouveau bug pour traiter le problème.

1. J'ai effectivement pu voir dans tes logs que les clefs des informations voltage/intensité/puissance/consommations ne sont pas les mêmes. Sur ma version deux l'unité (resp. mv, ma, mw, wh) sont accolés. Ce qui explique très probablement que ça ne remonte pas.
Je viens de faire une correction **sur github** (en effet, je suis en déplacement cette semaine, ça m'est difficile d'envoyer sur le market hors de chez moi). Du coup, je vous invite à refaire un test et me faire un retour.

1. Effectivement, tu mets le doigt sur une incohérence des informations remontées : P = U.I et ce n'est pas le cas (j'ai confirmé chez moi). J'ai une prise HS110 branchée sur une prise Zwave ce qui m'a permis de vérifier les informations. Selon mes tests, c'est la valeur "Puissance" qui sera correcte (à 3W près...) et donc celle de l'intensité qui serait incorrecte (puisque le voltage me remonte 230V à pi près).
Je ne peux pas y faire grand chose... le but du plugin est de renvoyer les informations telles qu'elles sont mises à disposition par Kasa... un petit avertissement serait peut-être nécessaire.

1. La valeur "total" est sensée représenter la "consommation" (chez moi, elle s'appelle total_wh). Il faut par contre avoir à l'esprit les contraintes de raffraichissement des informations (toutes les 15min -ou- commande raffraichir -ou- commande on/off). Là aussi, je n'ai pas eu le plaisir de vérifier la véracité de l'information, je ne fais que transmettre l'info de Kasa.

En résumé (pour ceux qui auraient à flemme de lire tout ;) ) **Mise à jour de kkasa disponible sur github et non sur le market** pour le moment. Nécessité de réinstaller les dépendances.

Encore merci à tous pour vos retours.

**Comment by Peboli** [comment]
Bonsoir @kavod ,

1. Oui j'ai anonymisé les coordonnées présentent dans le log, non pas que je redoute une bombe sur ma maison, mais c'est juste un réflexe.
J'ai fais la mise à jour via github et réinstallé les dépendances mais les coordonnées ainsi que le user et le mdp ne sont toujours pas anonymisés. J'ai regardé un peu dans le code mais mon niveau en PHP est plus que basique. Je vais ouvrir un bug report comme suggéré.

2. En cherchant la source du problème j'avais vu que tu divisais certaines valeur par 1000, mais je n'avais pas fais attention aux noms des clés par rapport à ce qu'il y avait dans la trace de debug ;)
Après le mise à jour les valeurs arrivent bien dans le widget. Merci de ton temps !

3. Pas de soucis pour cette incohérence sur la mesure de courant, elle n'est pas d'une grande importance.

4. Après observation, il semble que la valeur 'total' représente l'énergie consommée depuis le dernier passage à l'état 'ON' de la prise, et sur ma version (v.1.0) il faut que je divise la valeur remontée par 0.36 pour avoir la même valeur affichée que dans l'application Kasa (en kWh), ceci est à confirmer car cette prise alimente une lampe LED d'ambiance qui ne consomme pas grand chose, donc l'énergie consommée ne s'incrémente pas vite. Je ferai le test avec une charge plus importante pour essayer.

Merci à toi pour ton travail.

**Comment by LuffyyyffuL** [comment]
Bonjour,

Depuis la dernière màj, la puissance remonte correctement sur la HS110 v.1.0, par contre, j'ai un autre problème et cela sur les 2 versions HS110 v.1.0 + HS110 v.2.0 : 

Alors que les 2 prises sont utilisées en même temps avec un PC branché et allumé, entre 2 états, la puissance indique 0W alors que de la puissance est consommé : 

`[2018-12-06 21:30:03][SCENARIO] Start : Scenario execute automatiquement sur programmation.
[2018-12-06 21:30:03][SCENARIO] Exécution du sous-élément de type [condition] : if
[2018-12-06 21:30:03][SCENARIO] Evaluation de la condition : [111.642052 < 15] = Faux
[2018-12-06 21:30:03][SCENARIO] Exécution du sous-élément de type [action] : else
[2018-12-06 21:30:03][SCENARIO] Fin correcte du scénario
------------------------------------
[2018-12-06 21:30:07][SCENARIO] Start : Scenario execute automatiquement sur evenement venant de : [Prises electriques][PRISE PC][Power].
[2018-12-06 21:30:07][SCENARIO] Exécution du sous-élément de type [condition] : if
[2018-12-06 21:30:07][SCENARIO] Evaluation de la condition : [0 < 15] = Vrai
[2018-12-06 21:30:07][SCENARIO] Exécution du sous-élément de type [action] : then
[2018-12-06 21:30:07][SCENARIO] Pause de 30 seconde(s)
[2018-12-06 21:30:37][SCENARIO] Exécution d'un bloc élément : 298
[2018-12-06 21:30:37][SCENARIO] Exécution du sous-élément de type [condition] : if
[2018-12-06 21:30:37][SCENARIO] Evaluation de la condition : [0 < 15] = Vrai
[2018-12-06 21:30:37][SCENARIO] Exécution du sous-élément de type [action] : then
[2018-12-06 21:30:37][SCENARIO] Exécution de la commande [Prises électriques][PRISE PC][Off]
[2018-12-06 21:30:39][SCENARIO] Fin correcte du scénario
------------------------------------
[2018-12-06 21:30:39][SCENARIO] Start : Scenario execute automatiquement sur evenement venant de : [Prises electriques][PRISE PC][Power].
[2018-12-06 21:30:39][SCENARIO] Exécution du sous-élément de type [condition] : if
[2018-12-06 21:30:39][SCENARIO] Evaluation de la condition : [333.469423 < 15] = Faux
[2018-12-06 21:30:39][SCENARIO] Exécution du sous-élément de type [action] : else
[2018-12-06 21:30:39][SCENARIO] Fin correcte du scénario`

Une idée ?

Merci :)

**Comment by Peboli** [comment]
Bonjour @kavod ,

Je pense qu'il y un soucis quand il y a deux HS110 (et j'imagine plus que deux), tous les widgets des HS110 affichent la même chose et cela correspond apparemment aux données du dernier module introduit dans le système lors de la synchro avec Kasa.
En faisant un 'refresh' sur le widget n'affichant pas les bonnes données, les données correctes de la prise s'affichent, mais cela ne dure que jusqu'au prochain cron15 qui rapatrie les infos de toutes les prises.

**Comment by kavod** [comment]
@Peboli : j'ai ouvert le ticket #4 dédié à ton problème.

Je termine un déplacement professionnel (mon avion du retour vient d'être annulé :( ) et je regarde tout ça.

**Comment by kavod** [comment]
Hello Peboli,

Juste un petit message à ton attention car j'ai enfin eu le fin mot de l'histoire concernant la différence entre la puissance et le produit intensité/puissance.
Il s'agit en fait de la différence entre puissance active et puissance apparente.
Deux petit liens qui en parle : https://fr.wikipedia.org/wiki/Puissance_en_r%C3%A9gime_alternatif https://www.youtube.com/watch?v=IURKavCBUkE
La puissance remontée dans le plugin est bien la puissance active, c'est celle qui sera calculée par le compteur électrique.
J'ai du apprendre ça à l'école... mais il faut croire que ça ne m'a pas marqué ;)
