### ISSUE TITLE
Pour ce qui est des commandes, pourquoi la page ne correspond pas à la structure habituelle de Jeedom ?

### ISSUE THREAD

**Issue by kavod** [kavod/kkasa#27]
Pour ce qui est des commandes, pourquoi la page ne correspond pas à la structure habituelle de Jeedom ?
A savoir des commandes infos qui peuvent êtres liées à des actions comme ci-dessous.

![image](https://user-images.githubusercontent.com/16508054/52898395-af4b6c80-31dd-11e9-8876-90b337b3e2f5.png)

Ça permet d'utiliser un widget unique pour la commande et l'info, comme ceci au lieu d'avoir une indication d'état et deux commandes pour ON et OFF
![image](https://user-images.githubusercontent.com/16508054/52898411-ddc94780-31dd-11e9-964f-dc80664d4773.png)
![image](https://user-images.githubusercontent.com/16508054/52898418-e7eb4600-31dd-11e9-8350-0b7a6753adfb.png)

C'est juste un 'feature request', je ne sais pas vraiment ce que ça représente comme travail. Mais comme c'est un standard dans Jeedom je me dis que ça ne doit pas être trop compliqué ;)

_Originally posted by @Peboli in https://github.com/kavod/kkasa/issues/18#issuecomment-464334259_

**Comment by kavod** [comment]
Je me garde ça sous le coude pour mon retour.

Je me suis beaucoup inspiré de l'organisation du plugin openzwave qui ne me semble pas répondre à ce standard.
Si je ne me trompe pas, ce que tu me montres ressemble beaucoup à la présentation du plugin "virtuel".
Malgré tout, si ça peut apporter un avantage pas de soucis. Je garde ça en tête.

**Comment by Peboli** [comment]
D'accord, il n'y a pas d'urgence ;)

La capture provient d'une structure de commande du plugin ESPEASY, mais j'ai exactement la même dans le plugin Zwave avec une prise connectée Fibaro FGWPE/FGWPF Wall Plug Gen5

![image](https://user-images.githubusercontent.com/16508054/52900162-dfe9d100-31f2-11e9-9fa0-5ef52d5a64af.png)

**Comment by kavod** [comment]
Petite mise à jour qui, je l'espère, répondra à ton besoin.
Je te conseille de recréer tes équipements ou, au minimum, les commandes (en utilisant les nouveaux boutons dans l'onglet "Equipement"). Attention, si tu as des liens avec tes commandes actuelles (scénarios etc.) ils seront "cassés"... mais c'est le risque d'utiliser une bêta ;)

Je compte sur toi pour me disséquer le plugin pendant ces 2 semaines ;)

**Comment by Peboli** [comment]
Ça c'est du service rapide et efficace !
Je n'oserais pas dire que je n'en attendais pas autant ... ;)
Plus complet que ça il n'y a pas !
Encore merci pour ton investissement de temps à nos demandes.
Je vais disséquer ça comme il se doit et je te tiens au courant, mais ça m'a l'air de bien tourner.

**Comment by Peboli** [comment]
Bonjour,

Petite erreur hier et cette nuit.

![image](https://user-images.githubusercontent.com/16508054/52938574-4d683f80-3362-11e9-9286-912b9101d4a6.png)

**Comment by Peboli** [comment]
![kkasa3](https://user-images.githubusercontent.com/16508054/53285637-f9df6280-3762-11e9-8145-60bdce37a86a.PNG)

**Comment by kavod** [comment]
Issues spécifiques à ces 2 derniers problèmes créées.
Je ferme ce thread concernant la structure de la page "commandes"
