### ISSUE TITLE
[Local] Ajout des Equipements : 2e prise non détectée

### ISSUE THREAD

**Issue by Clem-** [kavod/kkasa#28]
Le premier scan local a bien trouvé la première prise.
Après le branchement d'une seconde prise et après avoir cliqué sur `Ajouter mes équipements`, le message "Synchronisation terminée mais aucun nouvel équipement joignable trouvé. Vérifiez l'application mobile Kasa" apparait.
Les deux prises sont bien présentes et pilotables dans l'application Kasa.

**Comment by kavod** [comment]
Hello,

Me voici de retour pour traiter tout ça.

Est-ce que par hasard, depuis, tu as pu réessayer voir si un second scan ne fonctionnerait pas mieux ? ("injoignabilité ponctuelle")
De plus, le mode "Contrôle à distance" est-il bien activé dans l'application Kasa pour la prise introuvable ?
Enfin, l'application Kasa est-elle bien fermée sur le mobile lorsque tu lances ton scan ?

**Comment by Clem-** [comment]
Je suis vraiment perdu avec ces deux modes de fonctionnement (local/remote).

Pour parer au problème de la non detection de la 2nd prise en local, j'ai du repasser en remote de façon à ce que le plugin récupère la liste des prises depuis Kasa.

Seulement, comment faire pour repasser en local ensuite (puisque le problème de la prise injoignable est toujours présent en Remote) ? Il n'y a en effet pas les informations des IP des prises et faire une nouvelle Synchro affiche qu'aucun nouvel équipement a été trouvé.

**Comment by kavod** [comment]
Hello,

J'ai prévu le cas : en mode local, si un équipement n'est pas joignable (et en l'absence d'adresse IP, il sera forcément injoignable), le plugin va automatiquement tenter de le retrouver sur le réseau local à partir de son deviceId et mettre à jour les infos IP et port.
Je viens de faire le test après un sync Cloud puis en passant en local : mes équipements continuent de fonctionner et les IP/ports sont bien déterminés (après un refresh des infos de chaque équipement).

Par contre, pour se faire, il réalise en fait un scan du réseau local. Donc si celui-ci ne fonctionne toujours pas au moment du sync, cette auto-détermination IP/port risque de ne pas mieux fonctionner.

Mais du coup je ne suis pas certain de comprendre ta situation : 
> puisque le problème de la prise injoignable est toujours présent en Remote

Tu me dis que, malgré de multiples tentatives, ta prise n'est toujours pas trouvée en mode local ?

**Comment by Clem-** [comment]
C'est malheureusement bien le cas.
En mode Cloud, le refresh fonctionne bien (ponctuellement évidement..). 
Je passe en Local, j'effectue un refresh et j'ai : 
> Device 8006B2345BC7067C61BE54601DD789CD19BCB26D not found on network

Si je clique sur "Ajouter mes équipements" j'ai :
> Synchronisation terminée mais aucun nouvel équipement joignable trouvé. Vérifiez l'application mobile Kasa

Dans les détails de ma prise, j'ai toujours "Local IP" et "Local port" de vide.

Il n'y a pas eu de nouvelles versions depuis, par hasard ? J'avais récupéré celle depuis GitHub avant que tu ne partes.

**Comment by kavod** [comment]
Hello,

Une petite correction a été faite le week-end dernier, mais ça ne changera rien à ton problème.
Il va falloir que je rende le debug un peu plus verbeux sur le scan des équipements car je ne vois pas bien pourquoi il ne la trouve pas. Ca peut arriver ponctuellement chez moi, mais si tu fais une nouvelle tentative 2min après en général ça passe.

Je te tiens au courant quand j'ai mis ça en place.

**Comment by kavod** [comment]
Hello,

Je viens d'ajouter quelques éléments de debug pour essayer de comprendre.
Peux-tu réinstaller la dernière version (branch v2) et retenter un scan local en niveau de log debug ?
Puis me pousser le résultat du debug.

Merci
