### ISSUE TITLE
Problème lorsqu'il y a plusieurs prises HS110 associées au même compte

### ISSUE THREAD

**Issue by kavod** [kavod/kkasa#4]
Je pense qu'il y un soucis quand il y a deux HS110 (et j'imagine plus que deux), tous les widgets des HS110 affichent la même chose et cela correspond apparemment aux données du dernier module introduit dans le système lors de la synchro avec Kasa.
En faisant un 'refresh' sur le widget n'affichant pas les bonnes données, les données correctes de la prise s'affichent, mais cela ne dure que jusqu'au prochain cron15 qui rapatrie les infos de toutes les prises.

Edit: J'ai essayé de désactiver la deuxième prise HS110, mais le problème reste le même.
J'ai joint le log debug.

[kkasa.log](https://github.com/kavod/kkasa/files/2657706/kkasa.log)

J'ai également eu ces deux évènements dans le centre message Jeedom : 

2018-12-06 13:45:14 | kkasa | Erreur sur la fonction cron15 du plugin : Class 'KKPA\Exceptions\KKPAClientException' not found |  
-- | -- | -- | --
  | 2018-12-05 13:45:14 | kkasa | Erreur sur la fonction cron15 du plugin : Class 'KKPA\Exceptions\KKPACurlErrorType' not found

Pas eu aujourd'hui par contre.

_Originally posted by @Peboli in https://github.com/kavod/kkasa/issues/1#issuecomment-445256738_

**Comment by kavod** [comment]
@Peboli : a priori, la correction était évidente et j'ai fais une correction sur une nouvelle branche "develop" de github.

/!\ Je n'ai pas eu la possibilité de tester ces corrections (d'où la création d'une nouvelle branche). Je te laisse me faire un retour. En cas de soucis, réinstaller la version master.

Merci

**Comment by Peboli** [comment]
Bonjour @kavod 
Cela ne semble pas fonctionner, valeurs toujours incohérentes et le refresh ne fonctionne plus sur aucun des deux widgets (roue tourne sans arrêt)
J'ai eu ce message dans le log Jeedom :

2018-12-07 18:30:03 | kkasa | Erreur sur la fonction cron15 du plugin : Cannot access empty property
-- | -- | --

**Comment by kavod** [comment]
Home sweet home.
Ca devrait mieux fonctionner comme ça (plus d'erreur de mon coté en tout cas).
Comme je ne peux réellement tester avec 2 prises (car... bah je n'en ai qu'une à disposition) les modifications sont sur la branch "develop".

Je te laisse donc refaire un test.

Merci

**Comment by Peboli** [comment]
Bonsoir @kavod,

Désolé mais cela ne fonctionne pas ...
J'ai chargé la branche 'develop' et réinstallé les dépendances.
Le refresh du widget ne fonctionne pas et le debug me donne une erreur 'Internal server error'
Si tu le souhaites je peux te donner un accès à mon compte Kasa pour avoir accès à deux prises HS110 et pouvoir tester en conditions réelles.

**Comment by kavod** [comment]
Damned!
Non, je crois que j'ai trouvé le problème (qui avait été corrigé sur la branch master). Tu peux refaire un test depuis la branch develop.
Si ça ne fonctionne toujours pas... alors on prendra cette option.

Désolé pour le contre-temps :-/

**Comment by Peboli** [comment]
Bonjour @kavod ,

Simple question, est-il nécessaire que je supprime les prises et que je les resynchronisent après une mise à jour depuis Git ? Ton dernier correctif ne me donne plus d'erreur lors de la demande de debug et le widget se rafraîchi bien, mais après le cron15 les valeurs affichées sur un des widgets sont toujours erronées et correspondent à celles de l'autre prise à peu de choses près.
J'ai l'impression que le syncRealtime() lancé par le cron15 récupère les données de la même prise deux fois de suite plutôt que les données de chaque prise, du moins c'est ce que je vois dans le log : 
[2018-12-10 09:30:04][DEBUG] : set: Current to 0.622565
[2018-12-10 09:30:04][DEBUG] : set: Voltage to 233.969794
[2018-12-10 09:30:04][DEBUG] : set: Power to 91.334511
[2018-12-10 09:30:04][DEBUG] : set: Consumption to 7.2
[2018-12-10 09:30:04][DEBUG] : set: State to 1
[2018-12-10 09:30:04][DEBUG] : set: Current to 0.63173
[2018-12-10 09:30:04][DEBUG] : set: Voltage to 233.949174
[2018-12-10 09:30:04][DEBUG] : set: Power to 93.014468
[2018-12-10 09:30:04][DEBUG] : set: Consumption to 7.2
[2018-12-10 09:30:04][DEBUG] : set: State to 1

Si je fais un 'refresh' manuellement sur le widget j'ai les bonnes valeurs : 
[2018-12-10 09:47:18][DEBUG] : set: Current to 0.012456
[2018-12-10 09:47:18][DEBUG] : set: Voltage to 230.889199
[2018-12-10 09:47:18][DEBUG] : set: Power to 0
[2018-12-10 09:47:18][DEBUG] : set: Consumption to 0.224
[2018-12-10 09:47:19][DEBUG] : set: State to 0

Ne soit pas désolé pour le contre-temps ... nous avons tous une vie à côté ;)

**Comment by Peboli** [comment]
Mail envoyé !
Bonne journée.

**Comment by kavod** [comment]
Comme vu par mail, le problème semble enfin réglé.
Je vais intégrer la modification à la branche master et pousser la mise à jour sur le market.

Merci !
