### ISSUE TITLE
500 : Internal Server Error lors de l'ajout d'un équipement

### ISSUE THREAD

**Issue by RayMee84** [kavod/kkasa#40]
Apparition d'un bandeau rouge et une erreur 500 lors de l'ajout d'un équipement.

Vidage des logs, plugin en niveau "debug", reproduction du bug.

Seule entrée dans le log  http.error  :

Jeedom Version : 4.0.61
Plugin 2020-02-18 05:07:06
(Sur un Nuc)

[Tue Oct 13 11:56:11.150447 2020] [:error] [pid 11872] [client 192.168.1.153:51861] PHP Fatal error:  Uncaught Error: Class 'kkasa' not found in /var/www/html/plugins/kkasa/core/ajax/kkasa.ajax.php:30
Stack trace:
#0 {main}
  thrown in /var/www/html/plugins/kkasa/core/ajax/kkasa.ajax.php on line 30, referer: http://192.168.1.101/index.php?v=d&m=kkasa&p=kkasa

Similaire à ce sujet sur le forum de la communauté :
https://community.jeedom.com/t/500-internal-server-error-lors-dajout-dequipements/37804

**Comment by marilleaufra** [comment]
Première installation du plugin et même problème sur mon installation.
Test de réinstallation toujours KO
Installation de la version beta toujours KO
Merci d'avance

**Comment by kavod** [comment]
Hello,

Merci pour ce retour. Je viens de comprendre ce qu'il se passe : une librairie dépendante requière à présent php 7.2 ou supérieur.
Je suis en train de chercher une alternative.

**Comment by marilleaufra** [comment]
Bonjour Brice et merci pour ta réponse.
Je viens d'upgrade ma distri et de passer en php 7.3.
Le plugin fonctionne ! merci pour le développement !

Le jeu. 15 oct. 2020 à 20:19, Brice GRICHY <notifications@github.com> a
écrit :

**Comment by RayMee84** [comment]
Merci !!
