### ISSUE TITLE
Jeedom v4 compatibility

### ISSUE THREAD

**Issue by Booyaabes** [kavod/kkasa#45]
Is this plugins compatible with Jeedom v4? 
At the moment, kkasa is not in the Jeedom v4 plugin compatibility list.

**Comment by kavod** [comment]
I confirm the plugin is working on my Jeedom V4 box.
Commit d9d95f7 (only available on develop/unstable branch for moment) add "v4 compatibility" flag on Jeedom market.

**Comment by Booyaabes** [comment]
OK, good news. Thx you!
