### ISSUE TITLE
KKPA\Exceptions\KKPACurlErrorType' not found

### ISSUE THREAD

**Issue by kavod** [kavod/kkasa#5]
Je pense qu'il y un soucis quand il y a deux HS110 (et j'imagine plus que deux), tous les widgets des HS110 affichent la même chose et cela correspond apparemment aux données du dernier module introduit dans le système lors de la synchro avec Kasa.
En faisant un 'refresh' sur le widget n'affichant pas les bonnes données, les données correctes de la prise s'affichent, mais cela ne dure que jusqu'au prochain cron15 qui rapatrie les infos de toutes les prises.

Edit: J'ai essayé de désactiver la deuxième prise HS110, mais le problème reste le même.
J'ai joint le log debug.

[kkasa.log](https://github.com/kavod/kkasa/files/2657706/kkasa.log)

J'ai également eu ces deux évènements dans le centre message Jeedom : 

2018-12-06 13:45:14 | kkasa | Erreur sur la fonction cron15 du plugin : Class 'KKPA\Exceptions\KKPAClientException' not found |  
-- | -- | -- | --
  | 2018-12-05 13:45:14 | kkasa | Erreur sur la fonction cron15 du plugin : Class 'KKPA\Exceptions\KKPACurlErrorType' not found

Pas eu aujourd'hui par contre.

_Originally posted by @Peboli in https://github.com/kavod/kkasa/issues/1#issuecomment-445256738_

**Comment by Peboli** [comment]
Bonjour @kavod ,

J'ai également ces messages dans les messages Jeedom :

2018-12-09 12:28:13 | kkasa | Erreur sur la fonction cron du plugin : Class 'KKPA\Exceptions\KKPACurlErrorType' not found |  
-- | -- | -- | --
  | 2018-12-08 03:59:12 | kkasa | Erreur sur la fonction cron du plugin : Class 'KKPA\Exceptions\KKPAClientException' not found |  
  | 2018-12-08 03:58:04 | kkasa | Erreur sur la fonction cron du plugin : Class 'KKPA\Exceptions\KKPADeviceException' not found

En pièce jointe le log http.error avec un paquet de message relatif au plugin.

[http.error.txt](https://github.com/kavod/kkasa/files/2660471/http.error.txt)

**Comment by kavod** [comment]
Cette erreur laisse à penser qu'il y a eu une erreur de connexion (temporaire ?)
Sauf bug reproductible, je ne pense pas pouvoir le résoudre.
Cependant, le message d'erreur n'est pas explicite. J'ai donc corrigé la levée d'exception qui devrait être de la forme : 
"Device is offline" ou "Request timeout"

La correction a été appliquée à la branche master.
Je te laisse tester et me tenir informé.

Merci

**Comment by Peboli** [comment]
Voici à titre informatif ce qui ressort suite aux modifications des levées d'exceptions :

2018-12-11 07:54:10 | kkasa | Erreur sur la fonction cron du plugin : Device is offline |  
-- | -- | -- | --
  | 2018-12-11 02:56:05 | kkasa | Erreur sur la fonction cron du plugin : Error -20003 |  
  | 2018-12-11 02:50:13 | kkasa | Erreur sur la fonction cron du plugin : Request timeout

**Comment by kavod** [comment]
Supposé résolu.

N'hésite pas à rouvrir l'anomalie en cas de répétition anormale de ce type d'erreur.
